DF-35
yee2542/FluentSearch-BFF pull request #4
Opened 2020-10-30 13:02 UTC by pcybxine

Up date and add ci

2021-01-05 19:06 UTC, yee2542 requested changes
Check

2021-01-05 19:06 UTC, yee2542 commented on test/user.e2e-spec.ts
> +    app.useGlobalPipes(new ValidationPipe());
set to use `transform:true`

2021-01-05 19:06 UTC, yee2542 commented on src/user/pipes/user.trim.pipe.ts
> +
may be we add `INCLUEDED_FIELD` to select only trim field to preventing for loss performance

2021-01-05 19:06 UTC, yee2542 commented on src/database/database.provider.ts
> +          pass: 'fluent-search-bff-db',
use this value from `ConfigModule`

2021-01-17 14:44 UTC, octobrekids commented on test/user-resolver.e2e-spec.ts
> +        console.log(res.body.data);
Don't forget to remove after debug ka

2021-01-17 15:22 UTC, octobrekids commented on src/user/user.module.ts
> +  providers: [UserService, UserResolver, ...userProivders],
please check spelling of `userProviders`

2021-01-17 15:34 UTC, octobrekids commented on src/user/user.providers.ts
> +export const userProivders: Provider[] = [
please check `userProviders` spelling

2021-01-17 15:40 UTC, octobrekids reviewed
Please check ka

2021-01-17 15:43 UTC, yee2542 approved these changes

2021-01-17 15:45 UTC, merged